teams
kurtcarpenter/TeamWerx pull request #34
Opened 2016-10-20 22:58 UTC by laanuk

2016-10-20 23:12 UTC, supersam654 commented on models/course.js
> +      course.teams.push(team)
Please do a check to make sure the team doesn't already exist.

2016-10-20 23:20 UTC, supersam654 requested changes

2016-10-20 23:20 UTC, supersam654 commented on models/student.js
> +      student.classes.push(classId)
Please add a check to make sure the class doesn't already exist.

2016-10-20 23:20 UTC, supersam654 commented on models/teams.js
> +  createdAt: { type: Date, expires: '12h', default: Date.now },
Why should this expire after 12 hours?

2016-10-20 23:20 UTC, supersam654 commented on models/teams.js
> +var TeamSchema = new Schema({
Please add `Professor._id` to the schema for access control.

2016-10-20 23:20 UTC, supersam654 commented on models/teams.js
> +exports.getById = function (id, cb) {
Please also require a professor_id on this find.

2016-10-20 23:20 UTC, supersam654 commented on models/teams.js
> +  Team.find({classId: classId}, cb)
Also include a professor_id here.

2016-10-20 23:20 UTC, supersam654 commented on models/teams.js
> +      team.members.push(member)
Add a check to make sure the member isn't already in the team.

2016-10-20 23:32 UTC, laanuk commented
done

2016-10-21 13:33 UTC, supersam654 approved these changes

2016-10-21 13:36 UTC, merged